preload = /home/emrecc/İndirilenler/furinawp3.jpg
preload = /home/emrecc/İndirilenler/anm9996.jpg
preload = /home/emrecc/İndirilenler/wallhaven-8g3xj1.png
preload = /home/emrecc/İndirilenler/reze.png
wallpaper = eDP-1, /home/emrecc/İndirilenler/reze.png
