wallpaper {
    monitor =
    path = /home/emrecc/.config/hypr/furinawp3.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = /home/emrecc/.config/hypr/anm9996.jpg
    fit_mode = cover
}
wallpaper {
    monitor =
    path = /home/emrecc/.config/hypr/wallhaven-8g3xj1.png
    fit_mode = cover
}
wallpaper {
    monitor = eDP-1
    path = /home/emrecc/.config/hypr/reze.png
    fit_mode = cover
}
splash = false
